### ISSUE TITLE
feather does not build with gcc-4.6

### ISSUE THREAD

**Issue by kevinushey** [wesm/feather#279]
Attempts to build can fail, with issues like:

```
g++ -std=c++0x -I/home/travis/R-bin/lib/R/include -DNDEBUG -I. -I/home/travis/R-bin/include -I"/home/travis/R/Library/Rcpp/include"   -fpic  -g -O2 -c RcppExports.cpp -o RcppExports.o
In file included from feather/api.h:24:0,
                 from feather_types.h:2,
                 from RcppExports.cpp:4:
./feather/common.h:24:28: error: both ‘const’ and ‘constexpr’ cannot be used here
./feather/common.h:25:28: error: both ‘const’ and ‘constexpr’ cannot be used here
In file included from feather/api.h:25:0,
                 from feather_types.h:2,
                 from RcppExports.cpp:4:
./feather/io.h:73:29: error: expected ‘;’ at end of member declaration
./feather/io.h:73:35: error: ‘override’ does not name a type
...
```

The simplest fix would be a patch to [compatibility.h](https://github.com/wesm/feather/blob/master/cpp/src/feather/compatibility.h), to apply the workarounds for `gcc <= 4.6` (ie, include `4.6` as a 'not quite there' C++11 compiler)

**Comment by zhouzhen1** [comment]
@kevinushey 
Is your patch enough? I am now getting a long list of errors like 
```
include/c++/4.6.3/limits:196:57: error: ISO C++ forbids in-class initialization of non-const static member 'is_specialized'
include/c++/4.6.3/limits:201:48: error: ISO C++ forbids in-class initialization of non-const static member 'digits'
```

I guess we still have to to use the gcc 4.9 toolchain?

R 3.2.3, feather 0.3.1

**Comment by sallydenschke** [comment]
Experiencing the same issue as @zhouzhen1 with R 3.1.2 when trying to install feather. Trying to install via CRAN, using the (default) .\rtools\gcc-4.6.3 raises error:

> package 'feather' is available as a source package but not as a binary
<br>
Installing with
`install.packages("feather", type="source")`
raises errors like the ones @zhouzhen1 reported.<br>
<br>
It also raises notes like

> note: 'int std::numeric_limits<unsigned int>::digits' is not const
and another error

> error: '_M_x' was not declared in this scope
<br>
Installation fails with 

> confused by earlier errors, bailing out<br>
make: *** [feather/feather-c.o] Error 1<br>
Warnung: Ausführung von Kommando 'make -f "Makevars" -f "C:/PROGRA~1/R/R-31~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-31~1.2/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="feather.dll" OBJECTS="RcppExports.o feather-read.o feather-types.o feather-write.o"' ergab Status 2<br>
ERROR: compilation failed for package 'feather'<br>
<br>

**Comment by wesm** [comment]
Closing in favor of the Linux build and packaging available in the `arrow` package
